### ISSUE TITLE
Error while building using Visual Studio 2017

### ISSUE THREAD

**Issue by karan-k-deepr** [discretelogics/TeaFiles.Cpp-Time-Series-Storage-in-Files#5]
1>------ Rebuild All started: Project: TeaFiles, Configuration: Release x64 ------
1>MemoryAccess.cpp
1>Unknown compiler version - please run the configure tests and report the results
1>d:\teafiles.cpp-master\lib\boost\interprocess\detail\os_file_functions.hpp(131): warning C4018: '>': signed/unsigned mismatch
1>Exceptions.cpp
1>NameValue.cpp
1>Unknown compiler version - please run the configure tests and report the results
1>d:\teafiles.cpp-master\lib\boost\uuid\uuid_io.hpp(62): warning C4456: declaration of 'i' hides previous local declaration
1>d:\teafiles.cpp-master\lib\boost\uuid\uuid_io.hpp(52): note: see declaration of 'i'
1>d:\teafiles.cpp-master\teafiles\base\namevalue.cpp(46): note: see reference to function template instantiation 'std::basic_ostream<char,std::char_traits<char>> &boost::uuids::operator <<<char,std::char_traits<char>>(std::basic_ostream<char,std::char_traits<char>> &,const boost::uuids::uuid &)' being compiled
1>FieldType.cpp
1>IO.cpp
1>d:\teafiles.cpp-master\teafiles\description\teafiledescription.h(24): error C2512: 'teatime::TimeScale': no appropriate default constructor available
1>d:\teafiles.cpp-master\teafiles\description\teafiledescription.h(14): note: see declaration of 'teatime::TimeScale'
1>Unknown compiler version - please run the configure tests and report the results
1>TeaFileCore.cpp
1>Unknown compiler version - please run the configure tests and report the results
1>Field.cpp
1>Streams.cpp
1>ContentSectionFormatter.cpp
1>Unknown compiler version - please run the configure tests and report the results
1>d:\teafiles.cpp-master\teafiles\description\teafiledescription.h(24): error C2512: 'teatime::TimeScale': no appropriate default constructor available
1>d:\teafiles.cpp-master\teafiles\description\teafiledescription.h(14): note: see declaration of 'teatime::TimeScale'
1>NameValueSectionFormatter.cpp
1>Unknown compiler version - please run the configure tests and report the results
1>d:\teafiles.cpp-master\teafiles\description\teafiledescription.h(24): error C2512: 'teatime::TimeScale': no appropriate default constructor available
1>d:\teafiles.cpp-master\teafiles\description\teafiledescription.h(14): note: see declaration of 'teatime::TimeScale'
1>TimeSectionFormatter.cpp
1>Unknown compiler version - please run the configure tests and report the results
1>d:\teafiles.cpp-master\teafiles\description\teafiledescription.h(24): error C2512: 'teatime::TimeScale': no appropriate default constructor available
1>d:\teafiles.cpp-master\teafiles\description\teafiledescription.h(14): note: see declaration of 'teatime::TimeScale'
1>WriteContext.cpp
1>d:\teafiles.cpp-master\teafiles\description\teafiledescription.h(24): error C2512: 'teatime::TimeScale': no appropriate default constructor available
1>d:\teafiles.cpp-master\teafiles\description\teafiledescription.h(14): note: see declaration of 'teatime::TimeScale'
1>ItemDescription.cpp
1>Unknown compiler version - please run the configure tests and report the results
1>TeaFileDescription.cpp
1>d:\teafiles.cpp-master\teafiles\description\teafiledescription.h(24): error C2512: 'teatime::TimeScale': no appropriate default constructor available
1>d:\teafiles.cpp-master\teafiles\description\teafiledescription.h(14): note: see declaration of 'teatime::TimeScale'
1>ReadContext.cpp
1>d:\teafiles.cpp-master\teafiles\description\teafiledescription.h(24): error C2512: 'teatime::TimeScale': no appropriate default constructor available
1>d:\teafiles.cpp-master\teafiles\description\teafiledescription.h(14): note: see declaration of 'teatime::TimeScale'
1>ItemSectionFormatter.cpp
1>Unknown compiler version - please run the configure tests and report the results
1>d:\teafiles.cpp-master\teafiles\description\teafiledescription.h(24): error C2512: 'teatime::TimeScale': no appropriate default constructor available
1>d:\teafiles.cpp-master\teafiles\description\teafiledescription.h(14): note: see declaration of 'teatime::TimeScale'
1>TextUtils.cpp
1>FormattedReader.cpp
1>Unknown compiler version - please run the configure tests and report the results
1>FormattedWriter.cpp
1>Unknown compiler version - please run the configure tests and report the results
1>FileIO.cpp
1>Generating Code...
1>Compiling...
1>HeaderManager.cpp
1>d:\teafiles.cpp-master\teafiles\description\teafiledescription.h(24): error C2512: 'teatime::TimeScale': no appropriate default constructor available
1>d:\teafiles.cpp-master\teafiles\description\teafiledescription.h(14): note: see declaration of 'teatime::TimeScale'
1>Unknown compiler version - please run the configure tests and report the results
1>WinUtils.cpp
1>d:\teafiles.cpp-master\teafiles\os\winutils.cpp(52): warning C4458: declaration of 'message' hides class member
1>d:\teafiles.cpp-master\teafiles\os\winutils.h(30): note: see declaration of 'teatime::CheckException::message'
1>Time.cpp
1>Unknown compiler version - please run the configure tests and report the results
1>TimeScale.cpp
1>Generating Code...
1>Done building project "TeaFiles.vcxproj" -- FAILED.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========

I have tried a lot to remove this error. but i don't know why it comes. 
Even constructor is written correctly.
Also, there is a class method name `static TeaFileDescription *FromFile(string fileName)` which is only declared but not defined. Is it intentionally or there is any fix to that?

**Comment by htmlboss** [comment]
I've fixed this error in my pull request (#7). I'm also planning to do a general overhaul of the code to bring it up to C++11 spec at least.

**Comment by snuup** [comment]
thx @htmlboss 
sry for the delay
