### ISSUE TITLE
Question : usage in compressed filesystem

### ISSUE THREAD

**Issue by xgdgsc** [discretelogics/TeaFiles.Cpp-Time-Series-Storage-in-Files#8]
Do you have any experience using teafiles and mmap in compressed filesystem like btrfs? What could the performance be like compared with uncompressed?

**Comment by snuup** [comment]
Appologize for the late reply, Good question!

I once tried it with NTFS on Windows and as far as I remember the system call for mapping returned an error, but I am not sure. basically, mmap is implemented at the file system layer and services like compression or sparse files (NTFS) are not available for it, which makes good sense.

What I do know, is that the combination of sparse files with mmap on Windows 8 causes very soon a blue screen error, something rare today.
